# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

staging:
  user-workflow:
    workflow-name: "ostium-trading-staging"

  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

production:
  user-workflow:
    workflow-name: "ostium-trading-production"

  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
