# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Aave lending starter-template (TypeScript).
# Config shape aligned with agentic LendingNodeConfig / LendingInputConfig for future invocation from the app.

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://arb-sepolia.g.alchemy.com/v2/_HarkXk6peAjgeCiE1LadowO9I0q2ZVh

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: arbitrum
      url: https://arb1.arbitrum.io/rpc
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://arb-sepolia.g.alchemy.com/v2/_HarkXk6peAjgeCiE1LadowO9I0q2ZVh
