# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

# ==========================================================================
staging:
  rpcs:
    - chain-name: arbitrum-1
      url: https://arb1.arbitrum.io/rpc

# ==========================================================================
production:
  rpcs:
    - chain-name: arbitrum-1
      url: https://arb1.arbitrum.io/rpc
