# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================

# ==========================================================================
staging:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://sepolia-rollup.arbitrum.io/rpc

# ==========================================================================
production:
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://arb1.arbitrum.io/rpc
