# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

staging:
  user-workflow:
    workflow-name: "lifi-swap-staging"

  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"

production:
  user-workflow:
    workflow-name: "lifi-swap-production"

  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
