# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
# Uniswap swap workflow. Config shape aligned with agentic SwapNodeConfig.

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "uniswap-swap-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "uniswap-swap-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
